sudo: true
language: node_js

matrix:
  include:
    - os: linux
      addons:
        firefox: latest
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          casks:
          - chromium

node_js: 8

addons:
  apt:
    packages:
      - chromium-browser
  