sudo: true
language: node_js

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.1

node_js: 8

addons:
  apt:
    packages:
      - chromium-browser

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install chromium; fi
  