sudo: true
language: node_js

matrix:
  include:
    - os: linux
      addons:
        firefox: latest
        apt:
          packages:
            - chromium-browser
    - os: osx
      osx_image: xcode10.1
      addons:
        chrome: stable

node_js: 8

addons:
  apt:
    packages:
      - chromium-browser
  