sudo: true
language: node_js

node_js: 
  - 8

dist: xenial

services:
  - xvfb

before_install:
  - sudo apt-get update
  - sudo apt-get -y install chromium-browser
  
matrix:
  include:
    - os: linux
      addons:
        firefox: latest
    - os: osx
      osx_image: xcode10.1
      addons:
        chrome: stable


  