sudo: true
language: node_js

matrix:
  include:
    - os: linux
      addons:
        firefox: latest
        apt:
          packages:
            - chromium-browser
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          casks:
          - chromium

node_js: 8
  